### ISSUE TITLE
Any way to add a second button?

### ISSUE THREAD

**Issue by Shogu** [StorageB/custom-command-toggle#2]
Hi & thanks a lot for this great extension.

I use it to activate a tiling extension when needed, however the tiling extension is disabled by defaut. It works very well and the UI is perfectly integrated.

Is there any way to have a second button, for another purpose?

Greetings from France!

Ogu

**Comment by StorageB** [comment]
I'm glad to hear you found the extension useful! Adding the option for a second button is a good idea, and something I would like to implement in the future. For now, you can manually make a copy of the extension. Hope this helps!
<br>

### Instructions for adding a second toggle button:

1. Make a copy of the "custom-command-toggle<span>@</span>storageb.github.com" extension folder located here:
   `~/.local/share/gnome-shell/extensions`
2. Rename the copied folder to `custom-command-toggle2@storageb.github.com`
3. In the metadata.json file:
   - rename the settings-schema to `"org.gnome.shell.extensions.custom-command-toggle2"`
   - rename the uuid to `"custom-command-toggle2@storageb.github.com"`
4. In the schemas folder:
   - rename the xml file to `org.gnome.shell.extensions.custom-command-toggle2.gschema.xml`
   - in that file, change the id and path:  
   `<schema id="org.gnome.shell.extensions.custom-command-toggle2" path="/org/gnome/shell/extensions/custom-command-toggle2/">`
   - delete the "gschemas.compiled" file.
5. Run these commands from the terminal to create a new gschemas.compiled file:
   `cd ~/.local/share/gnome-shell/extensions/custom-command-toggle2@storageb.github.com/`
   `glib-compile-schemas schemas`
6. Log out and log back in (or restart).

**Comment by Shogu** [comment]
Wow, thank you for the speed and precision of your response: the tips work wonderfully!

I configured the 2nd button to launch a script that activates a "tablet mode" on my hybrid laptop, enabling the "screen-rotate" extension and the virtual keyboard, given that I don't need these two elements most of the time.

It's very useful and much more elegant than a script in my terminal ^^ This looks exactly like what a default configuration could be (and it should be, tile and tablet modes could be default parts of Gnome-shell on a hybrid  workstation laptop)

Even the family can use this button, while they don't want to hear about the command line (alas!)

I guess I can make as many copies as I want, now I have to think of new uses.

And you as a developer, what do you activate with your own extension?

Cheers!

Ogu

**Comment by StorageB** [comment]
Glad it worked! Also, for executing commands, you may find the [Custom Command Menu](https://github.com/StorageB/custom-command-menu) extension useful if you haven't tried it. It's very similar except you run commands from a drop-down menu instead of a toggle button.

When I want to use my TV instead of my monitor for streaming or displaying content, I have a "Presentation" toggle. It turns off the night light, changes the audio output to HDMI, and turns on do not disturb mode. This is the command I have for the toggle on setting:

```
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false &&
pactl set-default-sink "alsa_output.pci-0000_07_00.1.hdmi-stereo" &&
gsettings set org.gnome.desktop.notifications show-banners false
```

I also used to have a script, but you can run [multiple commands](https://github.com/StorageB/custom-command-toggle?tab=readme-ov-file#commands) with the toggle button.

**Comment by StorageB** [comment]
Feature has been included in the v6 release.
