### ISSUE TITLE
disable statue icon in topbar

### ISSUE THREAD

**Issue by slooWne** [StorageB/custom-command-toggle#4]
my top bar is overcharged with a lot of other extension. custom-toggle-extension is great but when i enable the three button i created it's a bit to much in my top bar. 
could you add a functionality to disable this indicator or explain how to change the code to disable it ?
thanks a lot

**Comment by StorageB** [comment]
@Shogu - not sure if you're interested in this feature, but feel free to test this out as well.

**Comment by slooWne** [comment]
i tried, it works fine.

**Comment by StorageB** [comment]
Feature has been added.
