### ISSUE TITLE
Clicking a non-toggle button doesn't close quick settings  

### ISSUE THREAD

**Issue by efogdev** [StorageB/custom-command-toggle#5]
Hey, I'm not sure if it is intended, but I'd prefer to have this configurable. 
I made a script that opens an interactive zenity window and it is not ideal with the current behavior.
See the example (I need to click twice because the window is out of focus when opened):

https://github.com/user-attachments/assets/e8b9b019-8bf1-483d-82b4-504bffb107b1

Thanks for the extension! Great implementation.

**Comment by StorageB** [comment]
Hello! This is the default behavior of the quick settings menu, but I think that's a good idea to have this as a configurable option.

Try the manual fix below to see if it works for your use case. It immediately closes the menu after you click the toggle button, and focus goes to the newly opened window:

1. Navigate to the extension.js file located in your home directory here:
`~/.local/share/gnome-shell/extensions/custom-command-toggle@storageb.github.com`
2. Add the following line to the executeCommand function:
`Main.panel.closeQuickSettings();`
Screenshot:
![Screenshot from 2024-09-23 11-11-34](https://github.com/user-attachments/assets/a72ff682-1a67-4e98-9bc4-368670393d11)


3. Log out and back in or restart computer.

**Comment by EfogDev** [comment]
It works!

**Comment by StorageB** [comment]
Great! I'll include that as an option in the next release.

**Comment by StorageB** [comment]
Feature has been added. Thanks for the suggestion!
