### ISSUE TITLE
feature request : CLI commands to toggle buttons

### ISSUE THREAD

**Issue by mohamed776k776** [StorageB/custom-command-toggle#6]
i would like to be able to toggle buttons through the command line so that i can have a keyboard shortcut synced with the button
another way would be to be able to associate a keyboard shortcut to each button which way is easier would be nice
thanks so much for the amazing extension, i appreciate it so much <3.

**Comment by StorageB** [comment]
I'm glad to hear the extension has been useful for you!

Having the option to associate a keyboard shortcut with each button is a great idea. I will look into that and see if I can incorporate that into the next update. Thanks for the idea and feedback

**Comment by StorageB** [comment]
Keyboard shortcuts have been implemented. Thanks for the suggestion!
